# Generated by Django 3.2 on 2021-04-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
