# Generated by Django 3.2 on 2021-04-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_catalogue_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='price',
            field=models.IntegerField(verbose_name='Price(in kobo)'),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5, null=True),
        ),
    ]
